# Create regions

northeast              			= Region.create(name: 'Northeast')
mountain_west          			= Region.create(name: 'Mountain West')
southeast              			= Region.create(name: 'Southeast')
southwest              			= Region.create(name: 'Southwest')
northwest              			= Region.create(name: 'Northwest')
south                  			= Region.create(name: 'South')
middle_atlantic        			= Region.create(name: 'Middle Atlantic')
midwest                			= Region.create(name: 'Midwest')
alaska                 			= Region.create(name: 'Alaska')
hawaii_and_the_islands 			= Region.create(name: 'Hawaii and the Islands')

# Create states

alabama 						= southeast.states.create(name: 'Alabama', abbreviation: 'AL')
alaska 							= alaska.states.create(name: 'Alaska', abbreviation: 'AK')
arizona 						= southwest.states.create(name: 'Arizona', abbreviation: 'AZ')
arkansas 						= southeast.states.create(name: 'Arkansas', abbreviation: 'AR')
california 						= northwest.states.create(name: 'California', abbreviation: 'CA')
colorado 						= mountain_west.states.create(name: 'Colorado', abbreviation: 'CO')
connecticut 					= northeast.states.create(name: 'Connecticut', abbreviation: 'CT')
delaware 						= middle_atlantic.states.create(name: 'Delaware', abbreviation: 'DE')
florida 						= southeast.states.create(name: 'Florida', abbreviation: 'FL')
georgia 						= southeast.states.create(name: 'Georgia', abbreviation: 'GA')
hawaii 							= hawaii_and_the_islands.states.create(name: 'Hawaii', abbreviation: 'HI')
idaho 							= mountain_west.states.create(name: 'Idaho', abbreviation: 'ID')
illinois 						= midwest.states.create(name: 'Illinois', abbreviation: 'IL')
indiana 						= midwest.states.create(name: 'Indiana', abbreviation: 'IN')
iowa 							= midwest.states.create(name: 'Iowa', abbreviation: 'IA')
kansas 							= midwest.states.create(name: 'Kansas', abbreviation: 'KS')
kentucky 						= southeast.states.create(name: 'Kentucky', abbreviation: 'KY')
louisiana 						= south.states.create(name: 'Louisiana', abbreviation: 'LA')
maine 							= northeast.states.create(name: 'Maine', abbreviation: 'ME')
maryland 						= middle_atlantic.states.create(name: 'Maryland', abbreviation: 'MD')
massachusetts 					= northeast.states.create(name: 'Massachusetts', abbreviation: 'MA')
michigan 						= midwest.states.create(name: 'Michigan', abbreviation: 'MI')
minnesota 						= midwest.states.create(name: 'Minnesota', abbreviation: 'MN')
mississippi 					= southeast.states.create(name: 'Mississippi', abbreviation: 'MS')
missouri 						= midwest.states.create(name: 'Missouri', abbreviation: 'MO')
montana 						= mountain_west.states.create(name: 'Montana', abbreviation: 'MT')
nebraska 						= midwest.states.create(name: 'Nebraska', abbreviation: 'NE')
nevada 							= mountain_west.states.create(name: 'Nevada', abbreviation: 'NV')
new_hampshire 					= northeast.states.create(name: 'New Hampshire', abbreviation: 'NH')
new_jersey 						= northeast.states.create(name: 'New Jersey', abbreviation: 'NJ')
new_mexico 						= southwest.states.create(name: 'New Mexico', abbreviation: 'NM')
new_york 						= middle_atlantic.states.create(name: 'New York', abbreviation: 'NY')
north_carolina 					= southeast.states.create(name: 'North Carolina', abbreviation: 'NC')
north_dakota  					= mountain_west.states.create(name: 'North Dakota', abbreviation: 'ND')
ohio 							= midwest.states.create(name: 'Ohio', abbreviation: 'OH')
oklahoma 						= south.states.create(name: 'Oklahoma', abbreviation: 'OK')
oregon 							= northwest.states.create(name: 'Oregon', abbreviation: 'OR')
pennsylvania  					= middle_atlantic.states.create(name: 'Pennsylvania', abbreviation: 'PA')
rhode_island  					= northeast.states.create(name: 'Rhode Island', abbreviation: 'RI')
south_carolina 					= southeast.states.create(name: 'South Carolina', abbreviation: 'SC')
south_dakota  					= mountain_west.states.create(name: 'South Dakota', abbreviation: 'SD')
tennessee 						= southeast.states.create(name: 'Tennessee', abbreviation: 'TN')
texas 							= south.states.create(name: 'Texas', abbreviation: 'TX')
utah 							= southwest.states.create(name: 'Utah', abbreviation: 'UT')
vermont 						= northeast.states.create(name: 'Vermont', abbreviation: 'VT')
virginia 						= middle_atlantic.states.create(name: 'Virginia', abbreviation: 'VA')
washington 						= northwest.states.create(name: 'Washington', abbreviation: 'WA')
west_virginia 					= middle_atlantic.states.create(name: 'West Virginia', abbreviation: 'WV')
wisconsin 						= midwest.states.create(name: 'Wisconsin', abbreviation: 'WI')
wyoming 						= mountain_west.states.create(name: 'Wyoming', abbreviation: 'WY')
american_samoa 					= hawaii_and_the_islands.states.create(name: 'American Samoa', abbreviation: 'AS')
district_of_columbia 			= middle_atlantic.states.create(name: 'District of Columbia', abbreviation: 'DC')
federated_states_of_micronesia 	= hawaii_and_the_islands.states.create(name: 'Federated States of Micronesia', abbreviation: 'FM')
guam 							= hawaii_and_the_islands.states.create(name: 'Guam', abbreviation: 'GU')
marshall_islands 				= hawaii_and_the_islands.states.create(name: 'Marshall Islands', abbreviation: 'MH')
northern_mariana_islands 		= hawaii_and_the_islands.states.create(name: 'Northern Mariana Islands', abbreviation: 'MP')
palau 							= hawaii_and_the_islands.states.create(name: 'Palau', abbreviation: 'PW')
puerto_rico 					= hawaii_and_the_islands.states.create(name: 'Puerto Rico', abbreviation: 'PR')
virgin_islands 					= hawaii_and_the_islands.states.create(name: 'Virgin Islands', abbreviation: 'VI')

# Create parks

acadia = maine.parks.create(name: 'Acadia', web_extension: 'acad')
american_samoa_np = american_samoa.parks.create(name: 'American Samoa', web_extension: 'npsa')
arches = utah.parks.create(name: 'Arches', web_extension: 'arch')
badlands = south_dakota.parks.create(name: 'Badlands', web_extension: 'badl')
big_bend = texas.parks.create(name: 'Big Bend', web_extension: 'bibe')
biscayne = florida.parks.create(name: 'Biscayne', web_extension: 'bisc')
black_canyon_of_the_gunnison = colorado.parks.create(name: 'Black Canyon of the Gunnison', web_extension: 'blca')
bryce_canyon = utah.parks.create(name: 'Bryce Canyon', web_extension: 'brca')
canyonlands = utah.parks.create(name: 'Canyonlands', web_extension: 'cany')
capitol_reef = utah.parks.create(name: 'Capitol Reef', web_extension: 'care')
carlsbad_caverns = new_mexico.parks.create(name: 'Carlsbad Caverns', web_extension: 'cave')
channel_islands = california.parks.create(name: 'Channel Islands', web_extension: 'chis')
congaree = south_carolina.parks.create(name: 'Congaree', web_extension: 'cong')
crater_lake = oregon.parks.create(name: 'Crater Lake', web_extension: 'crla')
cuyahoga_valley = ohio.parks.create(name: 'Cuyahoga Valley', web_extension: 'cuva')
death_valley = california.parks.create(name: 'Death Valley', web_extension: 'deva')
denali = alaska.parks.create(name: 'Denali', web_extension: 'dena')
dry_tortugas = florida.parks.create(name: 'Dry Tortugas', web_extension: 'drto')
everglades = florida.parks.create(name: 'Everglades', web_extension: 'ever')
gates_of_the_arctic = alaska.parks.create(name: 'Gates of the Arctic', web_extension: 'gaar')
glacier = montana.parks.create(name: 'Glacier', web_extension: 'glac')
glacier_bay = alaska.parks.create(name: 'Glacier Bay', web_extension: 'glba')
grand_canyon = arizona.parks.create(name: 'Grand Canyon', web_extension: 'grca')
grand_teton = wyoming.parks.create(name: 'Grand Teton', web_extension: 'grte')
great_basin = nevada.parks.create(name: 'Great Basin', web_extension: 'grba')
great_sand_dunes = colorado.parks.create(name: 'Great Sand Dunes', web_extension: 'grsa')
great_smoky_mountains = north_carolina.parks.create(name: 'Great Smoky Mountains', web_extension: 'grsm')
guadalupe_mountains = texas.parks.create(name: 'Guadalupe Mountains', web_extension: 'gumo', )
haleakala = hawaii.parks.create(name: 'Haleakala', web_extension: 'hale')
hawaii_volcanoes = hawaii.parks.create(name: 'Hawaii Volcanoes', web_extension: 'havo')
hot_springs = arkansas.parks.create(name: 'Hot Springs', web_extension: 'hosp')
isle_royale = michigan.parks.create(name: 'Isle Royale', web_extension: 'isro')
joshua_tree = california.parks.create(name: 'Joshua Tree', web_extension: 'jotr')
katmai = alaska.parks.create(name: 'Katmai', web_extension: 'katm')
kenai_fjords = alaska.parks.create(name: 'Kenai Fjords', web_extension: 'kefj')
kings_canyon = california.parks.create(name: 'Kings Canyon', web_extension: 'kica')
kobuk_valley = alaska.parks.create(name: 'Kobuk Valley', web_extension: 'kova')
lake_clark = alaska.parks.create(name: 'Lake Clark', web_extension: 'lacl')
lassen_volcanic = california.parks.create(name: 'Lassen Volcanic', web_extension: 'lavo')
mammoth_cave = kentucky.parks.create(name: 'Mammoth Cave', web_extension: 'maca')
mesa_verde = colorado.parks.create(name: 'Mesa Verde', web_extension: 'meve')
mount_rainier = washington.parks.create(name: 'Mount Rainier', web_extension: 'mora')
north_cascades = washington.parks.create(name: 'North Cascades', web_extension: 'noca')
olympic = washington.parks.create(name: 'Olympic', web_extension: 'olym')
petrified_forest = arizona.parks.create(name: 'Petrified Forest', web_extension: 'pefo')
pinnacles = california.parks.create(name: 'Pinnacles', web_extension: 'pinn')
redwood = california.parks.create(name: 'Redwood', web_extension: 'redw')
rocky_mountain = colorado.parks.create(name: 'Rocky Mountain', web_extension: 'romo')
saguaro = arizona.parks.create(name: 'Saguaro', web_extension: 'sagu')
sequoia = california.parks.create(name: 'Sequoia', web_extension: 'sequ')
shenandoah = virginia.parks.create(name: 'Shenandoah', web_extension: 'shen')
theodore_roosevelt = north_dakota.parks.create(name: 'Theodore Roosevelt', web_extension: 'thro')
virgin_islands_np = virgin_islands.parks.create(name: 'Virgin Islands', web_extension: 'viis')
voyageurs = minnesota.parks.create(name: 'Voyageurs', web_extension: 'voya')
wind_cave = south_dakota.parks.create(name: 'Wind Cave', web_extension: 'wica')
wrangell_st_elias = alaska.parks.create(name: 'Wrangell St. Elias', web_extension: 'grte')
yellowstone = wyoming.parks.create(name: 'Yellowstone', web_extension: 'yell')
yosemite = california.parks.create(name: 'Yosemite', web_extension: 'yose')
zion = utah.parks.create(name: 'Zion', web_extension: 'zion')

# Create activities

hiking = Activity.create(name: 'Hiking')
biking = Activity.create(name: 'Biking')
camping = Activity.create(name: 'Camping')
wildlife_viewing = Activity.create(name: 'Wildlife Viewing')
boating = Activity.create(name: 'Boating')
campfires = Activity.create(name: 'Campfires')
skiing = Activity.create(name: 'Skiing')
local_dining = Activity.create(name: 'Local Dining')
guided_tours = Activity.create(name: 'Guided Tours')
historic_sites = Activity.create(name: 'Historic Sites')

# Create ratings

Rating.create(score: 10, park: acadia, activity: hiking)
Rating.create(score: 5, park: acadia, activity: biking)
Rating.create(score: 8, park: acadia, activity: camping)
Rating.create(score: 6, park: acadia, activity: wildlife_viewing)
Rating.create(score: 7, park: acadia, activity: boating)
Rating.create(score: 8, park: acadia, activity: campfires)
Rating.create(score: 2, park: acadia, activity: skiing)
Rating.create(score: 5, park: acadia, activity: local_dining)
Rating.create(score: 9, park: acadia, activity: guided_tours)
Rating.create(score: 4, park: acadia, activity: historic_sites)

Rating.create(score: 6, park: big_bend, activity: hiking)
Rating.create(score: 4, park: big_bend, activity: biking)
Rating.create(score: 5, park: big_bend, activity: camping)
Rating.create(score: 3, park: big_bend, activity: wildlife_viewing)
Rating.create(score: 6, park: big_bend, activity: boating)
Rating.create(score: 2, park: big_bend, activity: campfires)
Rating.create(score: 9, park: big_bend, activity: skiing)
Rating.create(score: 3, park: big_bend, activity: local_dining)
Rating.create(score: 2, park: big_bend, activity: guided_tours)
Rating.create(score: 5, park: big_bend, activity: historic_sites)

Rating.create(score: 9, park: guadalupe_mountains, activity: hiking)
Rating.create(score: 5, park: guadalupe_mountains, activity: biking)
Rating.create(score: 5, park: guadalupe_mountains, activity: camping)
Rating.create(score: 5, park: guadalupe_mountains, activity: wildlife_viewing)
Rating.create(score: 8, park: guadalupe_mountains, activity: boating)
Rating.create(score: 2, park: guadalupe_mountains, activity: campfires)
Rating.create(score: 4, park: guadalupe_mountains, activity: skiing)
Rating.create(score: 3, park: guadalupe_mountains, activity: local_dining)
Rating.create(score: 5, park: guadalupe_mountains, activity: guided_tours)
Rating.create(score: 8, park: guadalupe_mountains, activity: historic_sites)

Rating.create(score: 5, park: isle_royale, activity: hiking)
Rating.create(score: 7, park: isle_royale, activity: biking)
Rating.create(score: 3, park: isle_royale, activity: camping)
Rating.create(score: 4, park: isle_royale, activity: wildlife_viewing)
Rating.create(score: 1, park: isle_royale, activity: boating)
Rating.create(score: 2, park: isle_royale, activity: campfires)
Rating.create(score: 3, park: isle_royale, activity: skiing)
Rating.create(score: 7, park: isle_royale, activity: local_dining)
Rating.create(score: 7, park: isle_royale, activity: guided_tours)
Rating.create(score: 7, park: isle_royale, activity: historic_sites)

Rating.create(score: 5, park: voyageurs, activity: hiking)
Rating.create(score: 3, park: voyageurs, activity: biking)
Rating.create(score: 2, park: voyageurs, activity: camping)
Rating.create(score: 9, park: voyageurs, activity: wildlife_viewing)
Rating.create(score: 8, park: voyageurs, activity: boating)
Rating.create(score: 6, park: voyageurs, activity: campfires)
Rating.create(score: 5, park: voyageurs, activity: skiing)
Rating.create(score: 9, park: voyageurs, activity: local_dining)
Rating.create(score: 9, park: voyageurs, activity: guided_tours)
Rating.create(score: 3, park: voyageurs, activity: historic_sites)

Rating.create(score: 5, park: cuyahoga_valley, activity: hiking)
Rating.create(score: 6, park: cuyahoga_valley, activity: biking)
Rating.create(score: 4, park: cuyahoga_valley, activity: camping)
Rating.create(score: 5, park: cuyahoga_valley, activity: wildlife_viewing)
Rating.create(score: 6, park: cuyahoga_valley, activity: boating)
Rating.create(score: 7, park: cuyahoga_valley, activity: campfires)
Rating.create(score: 2, park: cuyahoga_valley, activity: skiing)
Rating.create(score: 4, park: cuyahoga_valley, activity: local_dining)
Rating.create(score: 2, park: cuyahoga_valley, activity: guided_tours)
Rating.create(score: 1, park: cuyahoga_valley, activity: historic_sites)